# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.choose_box = QtWidgets.QComboBox(self.centralwidget)
        self.choose_box.setGeometry(QtCore.QRect(280, 40, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.choose_box.setFont(font)
        self.choose_box.setCurrentText("請選擇")
        self.choose_box.setObjectName("choose_box")
        self.choose_box.setPlaceholderText("請選擇")
        self.choose_box.addItem("Basic")  
        self.choose_box.addItem("Bonus")
        

        self.Basic_or_Bonus_lb = QtWidgets.QLabel(self.centralwidget)
        self.Basic_or_Bonus_lb.setGeometry(QtCore.QRect(40, 40, 220, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.Basic_or_Bonus_lb.setFont(font)
        self.Basic_or_Bonus_lb.setObjectName("Basic_or_Bonus")
        self.Basic_or_Bonus_lb.setText("Basic_or_Bonus:")


        self.train_table_lb = QtWidgets.QLabel(self.centralwidget)
        self.train_table_lb.setGeometry(QtCore.QRect(30, 200, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.train_table_lb.setFont(font)
        self.train_table_lb.setText("TRAIN")
        self.train_table_lb.setObjectName("train_table_lb")

        self.test_table_lb = QtWidgets.QLabel(self.centralwidget)
        self.test_table_lb.setGeometry(QtCore.QRect(520, 200, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.test_table_lb.setFont(font)
        self.test_table_lb.setText("TEST")
        self.test_table_lb.setObjectName("test_table_lb")

        self.test_recall_table_lb = QtWidgets.QLabel(self.centralwidget)
        self.test_recall_table_lb.setGeometry(QtCore.QRect(1010, 200, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.test_recall_table_lb.setFont(font)
        self.test_recall_table_lb.setText("RECALL")
        self.test_recall_table_lb.setObjectName("test_recall_table_lb")




        self.train_table = QtWidgets.QTableWidget(self.centralwidget)
        self.train_table.setGeometry(QtCore.QRect(30, 250, 375, 350))
        self.train_table.setRowCount(12)
        self.train_table.setColumnCount(12)
        self.train_table.setObjectName("train_table")
        self.train_table.horizontalHeader().setVisible(False)
        self.train_table.horizontalHeader().setDefaultSectionSize(25)
        self.train_table.verticalHeader().setVisible(False)
        self.train_table.verticalHeader().setDefaultSectionSize(25)
        self.train_table.setFrameShape(QtWidgets.QFrame.Box)
        self.train_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.train_table.setStyleSheet("QTableWidget { border: 2px solid red; }")
        self.train_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.train_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        


        self.test_table = QtWidgets.QTableWidget(self.centralwidget)
        self.test_table.setGeometry(QtCore.QRect(520, 250, 375, 350))
        self.test_table.setRowCount(12)
        self.test_table.setColumnCount(12)
        self.test_table.setObjectName("test_table")
        self.test_table.horizontalHeader().setVisible(False)
        self.test_table.horizontalHeader().setDefaultSectionSize(25)
        self.test_table.verticalHeader().setVisible(False)
        self.test_table.verticalHeader().setDefaultSectionSize(25)
        self.test_table.setFrameShape(QtWidgets.QFrame.Box)
        self.test_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.test_table.setStyleSheet("QTableWidget { border: 2px solid red; }")
        self.test_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.test_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        
        self.test_recall_table = QtWidgets.QTableWidget(self.centralwidget)
        self.test_recall_table.setGeometry(QtCore.QRect(1010, 250, 375, 350))
        self.test_recall_table.setRowCount(12)
        self.test_recall_table.setColumnCount(12)
        self.test_recall_table.setObjectName("test_recall_table")
        self.test_recall_table.horizontalHeader().setVisible(False)
        self.test_recall_table.horizontalHeader().setDefaultSectionSize(25)
        self.test_recall_table.verticalHeader().setVisible(False)
        self.test_recall_table.verticalHeader().setDefaultSectionSize(25)
        self.test_recall_table.setFrameShape(QtWidgets.QFrame.Box)
        self.test_recall_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.test_recall_table.setStyleSheet("QTableWidget { border: 2px solid red; }")
        self.test_recall_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.test_recall_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)



        self.epoch_lb = QtWidgets.QLabel(self.centralwidget)
        self.epoch_lb.setGeometry(QtCore.QRect(520, 40, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.epoch_lb.setFont(font)
        self.epoch_lb.setText("Epoch:")
        self.epoch_lb.setObjectName("epoch_lb")

        self.epoch_box = QtWidgets.QSpinBox(self.centralwidget)
        self.epoch_box.setGeometry(QtCore.QRect(640, 40, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.epoch_box.setFont(font)
        self.epoch_box.setMinimum(1)
        self.epoch_box.setObjectName("epoch_box")

        self.train_btn = QtWidgets.QPushButton(self.centralwidget)
        self.train_btn.setGeometry(QtCore.QRect(780, 40, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.train_btn.setFont(font)
        self.train_btn.setText("Train!")
        self.train_btn.setObjectName("Train_btn")

        self.graph_box = QtWidgets.QComboBox(self.centralwidget)
        self.graph_box.setGeometry(QtCore.QRect(950, 40, 200, 50))
        self.graph_box.setPlaceholderText("請選擇")
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.graph_box.setFont(font)
        self.graph_box.setCurrentText("")
        self.graph_box.setObjectName("graph_box")

        MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
