from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1300, 550)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.data_btn = QtWidgets.QPushButton(self.centralwidget)
        self.data_btn.setGeometry(QtCore.QRect(20, 25, 400, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.data_btn.setFont(font)
        self.data_btn.setObjectName("data_btn")
        self.data_btn.setText(QtCore.QCoreApplication.translate("Window", "Please Select Data Set"))

        self.path_lbl = QtWidgets.QLabel(self.centralwidget)
        self.path_lbl.setGeometry(QtCore.QRect(450, 25, 400, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.path_lbl.setFont(font)
        self.path_lbl.setObjectName("path_lbl")
        self.path_lbl.setText(QtCore.QCoreApplication.translate("Window", "-"))

        self.train_btn = QtWidgets.QPushButton(self.centralwidget)
        self.train_btn.setEnabled(False)
        self.train_btn.setGeometry(QtCore.QRect(800 ,25, 300, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.train_btn.setFont(font)
        self.train_btn.setAutoFillBackground(True)
        self.train_btn.setAutoDefault(False)
        self.train_btn.setDefault(False)
        self.train_btn.setFlat(False)
        self.train_btn.setObjectName("train_btn")
        self.train_btn.setText(QtCore.QCoreApplication.translate("Window", "Start Training"))

        self.epoch_lbl = QtWidgets.QLabel(self.centralwidget)
        self.epoch_lbl.setGeometry(QtCore.QRect(20, 150, 100, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.epoch_lbl.setFont(font)
        self.epoch_lbl.setObjectName("epoch_lbl")
        self.epoch_lbl.setText(QtCore.QCoreApplication.translate("Window", "Epoch"))

        self.epoch_box = QtWidgets.QSpinBox(self.centralwidget)
        self.epoch_box.setGeometry(QtCore.QRect(140 , 150, 100, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.epoch_box.setFont(font)
        self.epoch_box.setMinimum(1)
        self.epoch_box.setMaximum(150)
        self.epoch_box.setProperty("value", 20)
        self.epoch_box.setObjectName("epoch_box")

        self.rate_lbl = QtWidgets.QLabel(self.centralwidget)
        self.rate_lbl.setGeometry(QtCore.QRect(300, 150, 150, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.rate_lbl.setFont(font)
        self.rate_lbl.setObjectName("rate_lbl")
        self.rate_lbl.setText(QtCore.QCoreApplication.translate("Window", "Learning Rate"))

        self.rate_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rate_box.setGeometry(QtCore.QRect(500, 150, 150, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.rate_box.setFont(font)
        self.rate_box.setDecimals(3)
        self.rate_box.setMaximum(1.0)
        self.rate_box.setSingleStep(0.1)
        self.rate_box.setProperty("value", 0.5)
        self.rate_box.setObjectName("rate_box")

        self.train_lbl = QtWidgets.QLabel(self.centralwidget)
        self.train_lbl.setGeometry(QtCore.QRect(20, 270, 200, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.train_lbl.setFont(font)
        self.train_lbl.setObjectName("train_lbl")
        self.train_lbl.setText(QtCore.QCoreApplication.translate("Window", "Training Accuracy:"))

        self.test_lbl = QtWidgets.QLabel(self.centralwidget)
        self.test_lbl.setGeometry(QtCore.QRect(380, 270, 200, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.test_lbl.setFont(font)
        self.test_lbl.setObjectName("test_lbl")
        self.test_lbl.setText(QtCore.QCoreApplication.translate("Window", "Testing Accuracy:"))

        self.weight_lbl = QtWidgets.QLabel(self.centralwidget)
        self.weight_lbl.setGeometry(QtCore.QRect(720, 270, 100, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.weight_lbl.setFont(font)
        self.weight_lbl.setObjectName("weight_lbl")
        self.weight_lbl.setText(QtCore.QCoreApplication.translate("Window", "Weight:"))

        self.train_result = QtWidgets.QLabel(self.centralwidget)
        self.train_result.setGeometry(QtCore.QRect(250, 270, 100, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.train_result.setFont(font)
        self.train_result.setObjectName("train_result")
        self.train_result.setText(QtCore.QCoreApplication.translate("Window", "-"))

        self.test_result = QtWidgets.QLabel(self.centralwidget)
        self.test_result.setGeometry(QtCore.QRect(600, 270, 100, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.test_result.setFont(font)
        self.test_result.setObjectName("test_result")
        self.test_result.setText(QtCore.QCoreApplication.translate("Window", "-"))

        self.weight_result = QtWidgets.QLabel(self.centralwidget)
        self.weight_result.setGeometry(QtCore.QRect(850, 270, 300, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.weight_result.setFont(font)
        self.weight_result.setMidLineWidth(0)
        self.weight_result.setWordWrap(True)
        self.weight_result.setObjectName("weight_result")
        self.weight_result.setText(QtCore.QCoreApplication.translate("Window", "-"))

        self.ratio_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ratio_lbl.setGeometry(QtCore.QRect(750, 150, 300, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.ratio_lbl.setFont(font)
        self.ratio_lbl.setObjectName("ratio_lbl")
        self.ratio_lbl.setText(QtCore.QCoreApplication.translate("Window", "Ratio of training data "))

        self.ratio_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ratio_box.setGeometry(QtCore.QRect(1050, 150, 150, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.ratio_box.setFont(font)
        self.ratio_box.setMaximum(1.0)
        self.ratio_box.setDecimals(4)
        self.ratio_box.setProperty("value", 0.6667)
        self.ratio_box.setSingleStep(0.01)
        self.ratio_box.setObjectName("ratio_box")

        self.warning_lbl = QtWidgets.QLabel(self.centralwidget)
        self.warning_lbl.setGeometry(QtCore.QRect(20, 400, 400, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.warning_lbl.setFont(font)
        self.warning_lbl.setObjectName("warning_lbl")
        self.warning_lbl.setText(QtCore.QCoreApplication.translate("Window", "Warning Message"))
        
        self.warning_result = QtWidgets.QLabel(self.centralwidget)
        self.warning_result.setGeometry(QtCore.QRect(250, 400, 400, 75))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        self.warning_result.setFont(font)
        self.warning_result.setObjectName("warning_result")
        self.warning_result.setText(QtCore.QCoreApplication.translate("Window", "-"))

        Window.setCentralWidget(self.centralwidget)
        Window.setWindowTitle(QtCore.QCoreApplication.translate("Window", "Project1"))
        QtCore.QMetaObject.connectSlotsByName(Window)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
